language: android

jdk: oraclejdk8

env:
 global:
  - ANDROID_TARGET=android-27
  - ANDROID_ABI=x86

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-x86-android-27

script:
  - android list targets
  - echo no | android create avd --force -n test -t android-23 --abi x86 -no-accel
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew installDebug